apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      replicas: 1
      containers:
      - name: backend
        image: docker.cs.vt.edu/jackp96/rewardreadydocker/api:latest
        imagePullPolicy: Always
        resources: {}
        ports:
        - containerPort: 9000
        env:
        - name: DATABASE_URI
          value: api-service
