apiVersion: apps/v1
kind: Deployment
metadata:
  name: rr-backend
spec:
  selector:
    matchLabels:
      app: rewardready1
      tier: backend
  template:
    metadata:
      labels:
        app: rewardready1
        tier: backend
    spec:
      containers:
        - name: rewardready-backend
          image: docker.cs.vt.edu/jackp96/rewardreadydocker/api:4.9
          imagePullPolicy: Always
          ports:
          - containerPort: 9000
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: rr-backend
spec:
  type: ClusterIP
  selector:
    app: rewardready1
    tier: backend
  ports:
  - port: 6868
    protocol: TCP
    targetPort: 9000
---