apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: rewardready1
      tier: frontend
  template:
    metadata:
      labels:
        app: rewardready1
        tier: frontend
    spec:
      containers:
      - name: rewardready-react
        image: docker.cs.vt.edu/jackp96/rewardreadydocker/client:2.7
        imagePullPolicy: Always
        resources: {}
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: rewardready1
    tier: frontend
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 3000
  type: LoadBalancer