apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: mysql:5.7
        resources: {}
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: db
          subPath: db
        env:
          - name: MYSQLDB_USER
            value: "root"
          - name: MYSQLDB_ROOT_PASSWORD
            value: "123456"
    volumes:
      - name: sqlscript
        configMap:
          name: database-init-script
          
