apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  selector:
    matchLabels:
      app: rewardready-database
  template:
    metadata:
      labels:
        app: rewardready-database
    spec:
      containers:
      - name: database
        image: docker.cs.vt.edu/jackp96/rewardreadydocker/mysql:1.2
        imagePullPolicy: Always
        stdin: true
        tty: true
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: db2
          subPath: db2
        env:
          - name: MYSQL_DATABASE
            value: rewardready
          - name: MYSQL_ROOT_PASSWORD
            value: "123456"
      volumes:
        - name: db2
          persistentVolumeClaim:
            claimName: db2
---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: rewardready
spec:
  type: ClusterIP
  selector:
    app: rewardready-database
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db2
  namespace: rewardready
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
